genie:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.30.101
    port: 3306
    database: CampusGenie
    username: hhy
    password: Hongyuan.1

  redis:
    host: 192.168.30.101
    port: 6379



